#spring:
#  application:
#    name: gateway
#  cloud:
#    gateway:
#    discovery:
#      locator:
#        enabled: true
#    routes:
#      - id: post-service
#        uri: lb://post-service
#        predicates:
#          - Path=/persons/**
#server:
#  port: 0
#eureka:
#  client:
#    serviceURL:
#      defaultZone: http://localhost:8761/eureka/